task_name: "ner"

# Clustering stage config
clustering:
  skip_embedding: false
  random_seed: 42
  batch_size: 64
  input_filename: "regplans-train.jsonl"
  embedding_model: "NbAiLab/nb-sbert-base"
  umap_n_components: 30
  min_cluster_size: 15
  min_samples: 1
  cluster_selection_epsilon: 0.3

# Evolution stage config
evolution:
  random_seed: 42
  subset_size: 5
  mu: 25 
  lambda_: 50  
  generations: 15
  cxpb: 0.6
  mutpb: 0.2
  tournsize: 2
  indpb: 0.2 
  inter_prob: 0.5 # Probability of inter-cluster mutation
  hof_size: 5
  model: "openai/gpt-oss-120b"
  temperature: 0.2
  max_tokens: 128

# Evaluation config
evaluation:
  validation_sample_ratio: 0.5 # Ratio of validation set to use
  model: "gpt-4o-mini"
  validation_file: "regplans-dev.conllu"
  prompt_template: |
    Du er en ekspert på Named Entity Recognition (NER). 
    Din oppgave er å identifisere entiteter som representerer feltnavn i tekstutdrag fra reguleringsplaner.

    De eneste gyldige etikettene er B-FELT (begynnelsen på et feltnavn) og I-FELT (fortsettelsen av det samme feltnavnet).

    Her er noen eksempler:

    {examples}

    Formuler svaret over flere linjer, med ett token per linje, og kun tokens som inngår i ett feltnavn. Hver linje skal inneholde tokenet etterfulgt av tilhørende etikett, atskilt med ett mellomrom.

    Tekst: '{input_text}'

    Entiteter:
